### ISSUE TITLE
Brotherhood Point / Service Hour Progress Bar

### ISSUE THREAD

**Issue by StevenMonty** [jdepp/ktp-website#12]
Add a progress bar to the user profile page that updates as the brother completes more service hours and brotherhood points to give a visual representation of their progress.

**Comment by jdepp** [comment]
@ZvontyFlugence are you displaying this progress bar on the profile page?

**Comment by ZvontyFlugence** [comment]
Yes, though would you want it to be displayed on both the secured and undecured modes of the profile, or just the secured mode, or only if its your own profile?

**Comment by jdepp** [comment]
I'd say don't show it on the unsecured profile page. Show it on the secured profile page and anyone can see it who's a logged in member.

**Comment by ZvontyFlugence** [comment]
Alright sounds good.
